spring:
  profiles:
    active: prod
  
  datasource:
    url: jdbc:postgresql://brais-claude-code.ch2aksogwa9r.us-east-1.rds.amazonaws.com:5432/braisclaude
    username: postgres
    password: ${RDS_PASSWORD:AQze2GCGJRu64lW9dsUJ}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  flyway:
    enabled: false # Disable for simplicity, using JPA auto-update

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 20

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      cloudwatch:
        enabled: false # Can be enabled with proper AWS SDK setup

logging:
  level:
    root: INFO
    com.company: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /home/ec2-user/app/application.log
    max-size: 50MB
    max-history: 10

# CORS configuration for production
cors:
  allowed-origins: 
    - "http://brais-claude-code.s3-website-us-east-1.amazonaws.com"
    - "https://brais-claude-code.s3-website-us-east-1.amazonaws.com"
  allowed-methods: 
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true